/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProviderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'plumber' : IDL.Null,
  'electrician' : IDL.Null,
  'mechanic' : IDL.Null,
});
export const Time = IDL.Int;
export const Provider = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'status' : ProviderStatus,
  'baseFeeINR' : IDL.Nat,
  'serviceType' : ServiceType,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'rejectionNote' : IDL.Opt(IDL.Text),
  'locationLabel' : IDL.Text,
  'registeredAt' : Time,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
  'inProgress' : IDL.Null,
  'completed' : IDL.Null,
  'cancelled' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'userName' : IDL.Text,
  'issueDescription' : IDL.Text,
  'createdAt' : Time,
  'userLat' : IDL.Float64,
  'userLng' : IDL.Float64,
  'userLocationLabel' : IDL.Text,
  'providerPrincipal' : IDL.Principal,
  'userContact' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RegisterProviderRequest = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'baseFeeINR' : IDL.Nat,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'locationLabel' : IDL.Text,
});
export const UpdateProviderProfileRequest = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'baseFeeINR' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'locationLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveProvider' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'getAllProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getActiveBookingByContact' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getApprovedProvidersByServiceType' : IDL.Func(
      [ServiceType],
      [IDL.Vec(Provider)],
      ['query'],
    ),
  'getBookingById' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByProvider' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBookingRequests' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyProfile' : IDL.Func([], [Provider], ['query']),
  'getPendingProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getProviderByPrincipal' : IDL.Func([IDL.Principal], [IDL.Opt(Provider)], ['query']),
  'getProvidersByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Provider)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markBookingComplete' : IDL.Func([IDL.Nat], [], []),
  'markBookingInProgress' : IDL.Func([IDL.Nat], [], []),
  'registerProvider' : IDL.Func([RegisterProviderRequest], [], []),
  'rejectProvider' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'respondToBooking' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBookingRequest' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'toggleAvailability' : IDL.Func([], [], []),
  'updateProviderLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'updateProviderProfile' : IDL.Func([UpdateProviderProfileRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProviderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'plumber' : IDL.Null,
    'electrician' : IDL.Null,
    'mechanic' : IDL.Null,
  });
  const Time = IDL.Int;
  const Provider = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'status' : ProviderStatus,
    'baseFeeINR' : IDL.Nat,
    'serviceType' : ServiceType,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'rejectionNote' : IDL.Opt(IDL.Text),
    'locationLabel' : IDL.Text,
    'registeredAt' : Time,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
    'inProgress' : IDL.Null,
    'completed' : IDL.Null,
    'cancelled' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'userName' : IDL.Text,
    'issueDescription' : IDL.Text,
    'createdAt' : Time,
    'userLat' : IDL.Float64,
    'userLng' : IDL.Float64,
    'userLocationLabel' : IDL.Text,
    'providerPrincipal' : IDL.Principal,
    'userContact' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RegisterProviderRequest = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'baseFeeINR' : IDL.Nat,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'locationLabel' : IDL.Text,
  });
  const UpdateProviderProfileRequest = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'baseFeeINR' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'locationLabel' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveProvider' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'getAllProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getActiveBookingByContact' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getApprovedProvidersByServiceType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(Provider)],
        ['query'],
      ),
    'getBookingById' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByProvider' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBookingRequests' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyProfile' : IDL.Func([], [Provider], ['query']),
    'getPendingProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getProviderByPrincipal' : IDL.Func([IDL.Principal], [IDL.Opt(Provider)], ['query']),
    'getProvidersByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Provider)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markBookingComplete' : IDL.Func([IDL.Nat], [], []),
    'markBookingInProgress' : IDL.Func([IDL.Nat], [], []),
    'registerProvider' : IDL.Func([RegisterProviderRequest], [], []),
    'rejectProvider' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'respondToBooking' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBookingRequest' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'toggleAvailability' : IDL.Func([], [], []),
    'updateProviderLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'updateProviderProfile' : IDL.Func([UpdateProviderProfileRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
