/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'userName' : string,
  'issueDescription' : string,
  'createdAt' : Time,
  'userLat' : number,
  'userLng' : number,
  'userLocationLabel' : string,
  'providerPrincipal' : Principal,
  'userContact' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null } |
  { 'inProgress' : null } |
  { 'completed' : null } |
  { 'cancelled' : null };
export interface Provider {
  'lat' : number,
  'lng' : number,
  'status' : ProviderStatus,
  'baseFeeINR' : bigint,
  'serviceType' : ServiceType,
  'principal' : Principal,
  'name' : string,
  'isAvailable' : boolean,
  'email' : string,
  'phone' : string,
  'licenseNumber' : string,
  'rejectionNote' : [] | [string],
  'locationLabel' : string,
  'registeredAt' : Time,
}
export type ProviderStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface RegisterProviderRequest {
  'lat' : number,
  'lng' : number,
  'baseFeeINR' : bigint,
  'serviceType' : ServiceType,
  'name' : string,
  'email' : string,
  'phone' : string,
  'licenseNumber' : string,
  'locationLabel' : string,
}
export type ServiceType = { 'plumber' : null } |
  { 'electrician' : null } |
  { 'mechanic' : null };
export type Time = bigint;
export interface UpdateProviderProfileRequest {
  'lat' : number,
  'lng' : number,
  'baseFeeINR' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
  'locationLabel' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveProvider' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'getAllProviders' : ActorMethod<[], Array<Provider>>,
  'getActiveBookingByContact' : ActorMethod<[string], [] | [Booking]>,
  'getApprovedProvidersByServiceType' : ActorMethod<
    [ServiceType],
    Array<Provider>
  >,
  'getBookingById' : ActorMethod<[bigint], Booking>,
  'getBookingsByProvider' : ActorMethod<[Principal], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookingRequests' : ActorMethod<[], Array<Booking>>,
  'getMyProfile' : ActorMethod<[], Provider>,
  'getPendingProviders' : ActorMethod<[], Array<Provider>>,
  'getProviderByPrincipal' : ActorMethod<[Principal], [] | [Provider]>,
  'getProvidersByEmail' : ActorMethod<[string], Array<Provider>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markBookingComplete' : ActorMethod<[bigint], undefined>,
  'markBookingInProgress' : ActorMethod<[bigint], undefined>,
  'registerProvider' : ActorMethod<[RegisterProviderRequest], undefined>,
  'rejectProvider' : ActorMethod<[Principal, string], undefined>,
  'respondToBooking' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBookingRequest' : ActorMethod<
    [Principal, string, string, string, number, number, string],
    bigint
  >,
  'toggleAvailability' : ActorMethod<[], undefined>,
  'updateProviderLocation' : ActorMethod<[number, number], undefined>,
  'updateProviderProfile' : ActorMethod<
    [UpdateProviderProfileRequest],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
