/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface RegisterProviderRequest {
    lat: number;
    lng: number;
    baseFeeINR: bigint;
    serviceType: ServiceType;
    name: string;
    email: string;
    phone: string;
    licenseNumber: string;
    locationLabel: string;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    userName: string;
    issueDescription: string;
    createdAt: Time;
    userLat: number;
    userLng: number;
    userLocationLabel: string;
    providerPrincipal: Principal;
    userContact: string;
}
export interface UpdateProviderProfileRequest {
    lat: number;
    lng: number;
    baseFeeINR: bigint;
    name: string;
    email: string;
    phone: string;
    locationLabel: string;
}
export interface Provider {
    lat: number;
    lng: number;
    status: ProviderStatus;
    baseFeeINR: bigint;
    serviceType: ServiceType;
    principal: Principal;
    name: string;
    isAvailable: boolean;
    email: string;
    phone: string;
    licenseNumber: string;
    rejectionNote?: string;
    locationLabel: string;
    registeredAt: Time;
}
export interface UserProfile {
    name: string;
}
export enum BookingStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export enum ProviderStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ServiceType {
    plumber = "plumber",
    electrician = "electrician",
    mechanic = "mechanic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveProvider(providerPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllProviders(): Promise<Array<Provider>>;
    getApprovedProvidersByServiceType(serviceType: ServiceType): Promise<Array<Provider>>;
    getBookingById(id: bigint): Promise<Booking>;
    getBookingsByProvider(providerPrincipal: Principal): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyBookingRequests(): Promise<Array<Booking>>;
    getMyProfile(): Promise<Provider>;
    getPendingProviders(): Promise<Array<Provider>>;
    getProvidersByEmail(email: string): Promise<Array<Provider>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerProvider(request: RegisterProviderRequest): Promise<void>;
    rejectProvider(providerPrincipal: Principal, note: string): Promise<void>;
    respondToBooking(bookingId: bigint, accept: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitBookingRequest(providerPrincipal: Principal, userName: string, userContact: string, issueDescription: string, userLat: number, userLng: number, userLocationLabel: string): Promise<bigint>;
    toggleAvailability(): Promise<void>;
    updateProviderLocation(lat: number, lng: number): Promise<void>;
    updateProviderProfile(request: UpdateProviderProfileRequest): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Provider as _Provider, ProviderStatus as _ProviderStatus, RegisterProviderRequest as _RegisterProviderRequest, ServiceType as _ServiceType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveProvider(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveProvider(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllProviders(): Promise<Array<Provider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProviders();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProviders();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedProvidersByServiceType(arg0: ServiceType): Promise<Array<Provider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedProvidersByServiceType(to_candid_ServiceType_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedProvidersByServiceType(to_candid_ServiceType_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_Booking_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_Booking_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByProvider(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByProvider(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByProvider(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookingRequests(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookingRequests();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookingRequests();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Provider> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_Provider_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_Provider_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingProviders(): Promise<Array<Provider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingProviders();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingProviders();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProvidersByEmail(arg0: string): Promise<Array<Provider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvidersByEmail(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvidersByEmail(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerProvider(arg0: RegisterProviderRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProvider(to_candid_RegisterProviderRequest_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProvider(to_candid_RegisterProviderRequest_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rejectProvider(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectProvider(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectProvider(arg0, arg1);
            return result;
        }
    }
    async respondToBooking(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToBooking(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitBookingRequest(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async toggleAvailability(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAvailability();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAvailability();
            return result;
        }
    }
    async updateProviderLocation(arg0: number, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProviderLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProviderLocation(arg0, arg1);
            return result;
        }
    }
    async updateProviderProfile(arg0: UpdateProviderProfileRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProviderProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProviderProfile(arg0);
            return result;
        }
    }
}
function from_candid_BookingStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderStatus): ProviderStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Provider_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Provider): Provider {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    userName: string;
    issueDescription: string;
    createdAt: _Time;
    userLat: number;
    userLng: number;
    userLocationLabel: string;
    providerPrincipal: Principal;
    userContact: string;
}): {
    id: bigint;
    status: BookingStatus;
    userName: string;
    issueDescription: string;
    createdAt: Time;
    userLat: number;
    userLng: number;
    userLocationLabel: string;
    providerPrincipal: Principal;
    userContact: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n15(_uploadFile, _downloadFile, value.status),
        userName: value.userName,
        issueDescription: value.issueDescription,
        createdAt: value.createdAt,
        userLat: value.userLat,
        userLng: value.userLng,
        userLocationLabel: value.userLocationLabel,
        providerPrincipal: value.providerPrincipal,
        userContact: value.userContact
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    status: _ProviderStatus;
    baseFeeINR: bigint;
    serviceType: _ServiceType;
    principal: Principal;
    name: string;
    isAvailable: boolean;
    email: string;
    phone: string;
    licenseNumber: string;
    rejectionNote: [] | [string];
    locationLabel: string;
    registeredAt: _Time;
}): {
    lat: number;
    lng: number;
    status: ProviderStatus;
    baseFeeINR: bigint;
    serviceType: ServiceType;
    principal: Principal;
    name: string;
    isAvailable: boolean;
    email: string;
    phone: string;
    licenseNumber: string;
    rejectionNote?: string;
    locationLabel: string;
    registeredAt: Time;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        status: from_candid_ProviderStatus_n6(_uploadFile, _downloadFile, value.status),
        baseFeeINR: value.baseFeeINR,
        serviceType: from_candid_ServiceType_n8(_uploadFile, _downloadFile, value.serviceType),
        principal: value.principal,
        name: value.name,
        isAvailable: value.isAvailable,
        email: value.email,
        phone: value.phone,
        licenseNumber: value.licenseNumber,
        rejectionNote: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.rejectionNote)),
        locationLabel: value.locationLabel,
        registeredAt: value.registeredAt
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): BookingStatus {
    return "pending" in value ? BookingStatus.pending : "accepted" in value ? BookingStatus.accepted : "declined" in value ? BookingStatus.declined : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ProviderStatus {
    return "pending" in value ? ProviderStatus.pending : "approved" in value ? ProviderStatus.approved : "rejected" in value ? ProviderStatus.rejected : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    plumber: null;
} | {
    electrician: null;
} | {
    mechanic: null;
}): ServiceType {
    return "plumber" in value ? ServiceType.plumber : "electrician" in value ? ServiceType.electrician : "mechanic" in value ? ServiceType.mechanic : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Provider>): Array<Provider> {
    return value.map((x)=>from_candid_Provider_n4(_uploadFile, _downloadFile, x));
}
function to_candid_RegisterProviderRequest_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterProviderRequest): _RegisterProviderRequest {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    baseFeeINR: bigint;
    serviceType: ServiceType;
    name: string;
    email: string;
    phone: string;
    licenseNumber: string;
    locationLabel: string;
}): {
    lat: number;
    lng: number;
    baseFeeINR: bigint;
    serviceType: _ServiceType;
    name: string;
    email: string;
    phone: string;
    licenseNumber: string;
    locationLabel: string;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        baseFeeINR: value.baseFeeINR,
        serviceType: to_candid_ServiceType_n11(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        email: value.email,
        phone: value.phone,
        licenseNumber: value.licenseNumber,
        locationLabel: value.locationLabel
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    plumber: null;
} | {
    electrician: null;
} | {
    mechanic: null;
} {
    return value == ServiceType.plumber ? {
        plumber: null
    } : value == ServiceType.electrician ? {
        electrician: null
    } : value == ServiceType.mechanic ? {
        mechanic: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
